drone: #namespace
    task_and_robot_environment_name: 'ParrotDroneGoto-v0'
    ros_ws_abspath: "/home/basha/Hassaan/catkin_workspaces/openairos_ws"
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 1000
    nsteps: 1000

